---
title: "Untitled"
author: "Harald Kliems"
date: "1/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(jsonlite)
library(tidyverse)
library(sf)
library(tmap)
library(lubridate)
library(hrbrthemes)
```

```{r}
download.file("https://CommunityMaps.wi.gov/crash/public/crashesKML.do?filetype=json&startyear=2000&en
dyear=2021&injsvr=K&county=dane", "test.json")

df <- st_read("test.json")

crashes <- df %>% 
  mutate(date = mdy(date),
         totfatl = as.numeric(totfatl))

tmap_mode("view")

crashes %>% 
  filter(muniname == "MADISON") %>% 
  filter(year(date)>2020) %>% 
  mutate(fat_plot = totfatl/500) %>% 
tm_shape() +
  tm_dots()
```

```{r}
crashes %>% 
  filter(muniname == "MADISON") %>% 
  group_by(year = year(date)) %>% 
  summarize(fatalities = sum(totfatl)) %>% 
  ggplot(aes(year, fatalities)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Traffic fatalities in Madison, 2001–2021",
       caption = "Data: Community Maps. https://CommunityMaps.wi.gov/") +
  xlab(element_blank()) +
  geom_vline(aes(xintercept = decimal_date(date("2019-07-14"))+1), color = "white") +
  geom_text(aes(label = fatalities), nudge_y = 1) +
  geom_text(aes(x = decimal_date(date("2019-07-14")), label = "Madison adopts\n Vision Zero", y = 5)) +
  theme_modern_rc()
```

Peter wanted numbers for Sun Prairie. The numbers are too low. So let's do fatal and serious injuries.

```{r}
download.file("https://CommunityMaps.wi.gov/crash/public/crashesKML.do?filetype=json&startyear=2000&en
dyear=2021&injsvr=K&injsvr=A&county=dane", "deadly_and_serious.json")
```

```{r}
df <- st_read("deadly_and_serious.json")

dead_severe <- df %>% 
  mutate(date = mdy(date),
         totfatl = as.numeric(totfatl),
         totinj = as.numeric(totinj))

dead_severe %>% 
  filter(muniname == "SUN PRAIRIE") %>% 
  group_by(year = year(date)) %>% 
  summarize(fatalities = sum(totfatl),
            injuries = sum(totinj),
            fat_inj = fatalities + injuries) %>% 
  ggplot(aes(year, fat_inj)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Traffic fatalities and severe injuries in Sun Prairie, 2001–2021",
       caption = "Data: Community Maps. https://CommunityMaps.wi.gov/") +
  xlab(element_blank()) +
  ylab("Number of fatalities and severe injuries") +
  geom_text(aes(label = fat_inj), nudge_y = 2) +
  theme_modern_rc()


```

